### ISSUE TITLE
Output right shifted and incorrect/missing samples around 0 Hz

### ISSUE THREAD

**Issue by dayalannair** [dayalannair/FMCW_FFT_Radar#29]
For now, this bug is left for future work for two reasons:

1. It can be easily corrected/accounted for 
2. The bug is small yet not obvious
3. The issue is around 0 Hz/DC which is next to/ inside the CW transmitter feed through region. The radar is not expected to detect targets this close to it.
4. Time saving

Current focus is to send/receive multiple sweeps/FFTs which is just an outer loop in the python script

**Comment by dayalannair** [comment]
### Circshift -1 units and set last 2 samples = 3rd last sample (hold)
![image](https://user-images.githubusercontent.com/34541777/175467403-a8a1979f-ee7f-4e29-be80-4f6b88ef7cda.png)

**Comment by jpt13653903** [comment]
So you actually have only one wrong sample -- not bad.

You still need to change your scale to log-scale...

**Comment by dayalannair** [comment]
Yes, though here it was two. Managed to get it to be only the first sample thats wrong - which is actually just a duplicate of the second sample... I may be able to solve this as it means that the first sample in the buffer is read twice.

**Comment by dayalannair** [comment]
### FIXED
