### ISSUE TITLE
FFT Improvements

### ISSUE THREAD

**Issue by dayalannair** [dayalannair/FMCW_FFT_Radar#3]
Hi @jpt13653903 
After adding Gaussian noise of up to 5 bits (noise between 0 and 32):
`n = 32*rand(200,1)';
I_row = round(I_row + n);
Q_row = round(Q_row + n);`

- The result did not change. I verified that the input data is as required. Not sure if adding more noise (i.e. increasing noise magnitude) will change FFT results. The rounding was needed to create fixed point input data.
- The floating point option in the FFT IP is for the case of floating point input data. I see that adding the noise to my real data converts the integer ADC value to a double precision value. I will try using this as the FFT input.

I will investigate these points further.

**Comment by jpt13653903** [comment]
- 12 dB is 2 bits, not 5...  5 will work, but it's excessive.
- You're adding the "same" noise to I and Q.  They should actually be independent.
- The FFT must change (i.e. the noise floor should rise).  If it does not, you're doing something wrong.

**Comment by dayalannair** [comment]
Ah okay. Will generate separate noise. IQ has a 90 deg phase shift, so should the noise have a 90 deg shift (not sure if that makes complete sense).
I.t.o bits, that makes sense as its a voltage, so 20log10(2^2) = 12dB. So for the max signal 20log10(2^12) = 72 dB the noise floor is around 60dB below. Also thinking now that there is no real headroom i.e. data goes up to the max value 4096 though the hardware etc was probably correctly designed --> out of scope of this project.

**Comment by jpt13653903** [comment]
No -- I and Q really are independent.  If you use a Gaussian distribution for I and Q, the magnitude ends up with a Raleigh distribution, and the phase with a uniform distribution.  I'll leave it as an exercise to figure out why that is... ;-)

See [here](https://en.wikipedia.org/wiki/Quantization_(signal_processing)#Quantization_noise_model) for a summary on signal-to-quantisation-noise on a sinusoidal signal.

**Comment by dayalannair** [comment]
I have managed to boil it down to this: the FFT possibly outputs a floating point value as stated below:
![image](https://user-images.githubusercontent.com/34541777/173663026-dde6d895-915a-42f9-9fca-5a220cff6ee1.png)
I am using the unscaled output, so the number may be full-precision (first point). I think this means single precision, Another option is that the data format parameter refers to both input and output data (so I could just have the input as .0000). 

However, the output is of size 24 bits per Im and Re, so it cannot be 32 bit precision. A final concern is the 'Phase Factor' parameter which I cannot find much info on. I have ignored it so far since here we are concerned with magnitude.

**Comment by jpt13653903** [comment]
Phase is important if you want to follow the FFT with coherent integration...  By that is a topic for another day.

I would stick to fixed-point.  The price you pay in performance and area (for floating point) is generally not worth the effort.

**Comment by dayalannair** [comment]
### Set input size to 16 bits, with the 4 MSBs set to 0
This was done as it seems the core is interpreting the unsigned input as 2's complement.
If the data is plotted as signed decimal, one can see the larger magnitude values wrapping around:
![image](https://user-images.githubusercontent.com/34541777/173779580-9699047f-085c-4723-88b8-12b921405c7a.png)

The plot below shows that the real FFT is correct. This is the case for inputs of 12 bit increased to 16 bit without sign extension since the values are unsigned:
![image](https://user-images.githubusercontent.com/34541777/173779263-624f85ce-aece-4552-b438-13847d90ec78.png)
For reference, when keeping the input as the original 12 bits, both the real and imaginary parts are different:
![image](https://user-images.githubusercontent.com/34541777/173781230-64276dae-6049-4d51-aaad-b76d84a48fb2.png)

**Comment by dayalannair** [comment]
ISSUE RESOLVED: extended 12 bit to 16 with zeros in MSB. This prevents unsigned being used as if 2s complement
