### ISSUE TITLE
Gen Bitstream Vivado observation

### ISSUE THREAD

**Issue by dayalannair** [dayalannair/FMCW_FFT_Radar#30]
If it says files unchanged, it means vivado did not 'register' that you changed the file. Does not seem to happen when using built in editor. May just be temporary bug

**Comment by dayalannair** [comment]
### Solution

Refresh hierarchy manually when this bug occurs. open file in local editor and see that changes are there. can also see it if the file is open in local editor and no reload option is present (file outdated)

**Comment by jpt13653903** [comment]
Vivado does have a few bugs like this, yes.  Best solution I found is the manual refresh you're talking about.
