### ISSUE TITLE
Performance comparison

### ISSUE THREAD

**Issue by dayalannair** [dayalannair/FMCW_FFT_Radar#35]
Is it fine to use the simulation FFT execution time as a measure of the actual execution time? for comparison with the matlab one. I dont think theres much speed up (if any) for such a small transform though may be nice to present

**Comment by jpt13653903** [comment]
That is fine

That said, I'm much more  interested in the fact that it is working at all.  You'll probably find Matlab is faster.

**Comment by dayalannair** [comment]
Agreed. I was thinking that getting it working - ensuring output is valid - is the aim of the project. Determining performance is left as future work as it requires increasing the transform length etc
