### ISSUE TITLE
FFT Fixed - is method suitable?

### ISSUE THREAD

**Issue by dayalannair** [dayalannair/FMCW_FFT_Radar#5]
Hi @jpt13653903 

I have fixed the issue by increasing the input bit width to 16 bits and then placed zeros in the MSBs to prevent the unsigned input being interpreted as 2's complement. The output values are 32 bit each. Here are the results:
![image](https://user-images.githubusercontent.com/34541777/173808211-70869682-9079-49c4-8d99-e43e43223bf3.png)
![image](https://user-images.githubusercontent.com/34541777/173808269-0304a5b5-59b7-425a-b7e9-e32189a3082e.png)
I will now begin working on the system for transferring data back to the PC. Once this is working on the board, is the project complete? Do I need to add any other features e.g. multi channel FFT? or would that just be a bonus.

**Comment by jpt13653903** [comment]
Extending the input is perfectly fine.  You have to match the interface to what you've got on the other side.

Anything more than that is bonus.  If you can inject data, do the FFT, pull out the data at the other end and show that the Matlab result is the same, that is plenty :-)
