### ISSUE TITLE
Data transfer methods

### ISSUE THREAD

**Issue by dayalannair** [dayalannair/FMCW_FFT_Radar#6]
1. Preliminary method: data stored in output dual port BRAM. Once storage is complete, data is streamed to PC
2. Desired method, to be attempted after (1): Use a FIFO buffer between FFT and PC to allow data points to be streamed while the FFT is still being computed. This is (so far) the most efficient method.

To do:

1. Connect UART packetiser to FFT interface module
2. Connect FFT start/enable to a push button
3. Set up python program for collecting the streamed data.

**Comment by jpt13653903** [comment]
Awesome :-)
